### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by dzheltkov** [UdalovaES/Linked_lists_HW#1]
1) Проект не компилируется, так как в main.cpp вы включаете файл "node.h" вместо "Node.h".

2) Нет деструктора, при уничтожении объекта память не очищается, происходит её утечка.

**Comment by UdalovaES** [comment]
Исправила замечания

**Comment by dzheltkov** [comment]
Задание зачтено, однако для LinkedList конструктор по умолчанию не очень хорошо сделан.
Надо бы написать `Node* Head = nullptr;` вместо `Node* Head;`
